mkdir src
mkdir src/test
mkdir src/test/resources
mkdir src/test/java
mkdir src/test/java/it
mkdir src/test/java/it/twenfir
mkdir src/test/java/it/twenfir/ddsparser
mkdir src/test/java/it/twenfir/ddsparser/ast
mkdir src/main
mkdir src/main/java
mkdir src/main/java/it
mkdir src/main/java/it/twenfir
mkdir src/main/java/it/twenfir/ddsparser
mkdir src/main/java/it/twenfir/ddsparser/ast
mkdir src/main/antlr4
mkdir src/main/antlr4/it
mkdir src/main/antlr4/it/twenfir
mkdir src/main/antlr4/it/twenfir/ddsparser
